ARG DOTNET_VERSION=10.0
ARG BUILD_CONFIGURATION=Staging
ARG BUILD_PLATFORM=linux-musl-x64

# Stage 1: Build the application
FROM mcr.microsoft.com/dotnet/sdk:"${DOTNET_VERSION}" AS build
WORKDIR /src
COPY ["../../orders_outbox.slnx", "out/"]
COPY ["../../Directory.Packages.props", "out/"]
COPY ["src/app.api/app.api.csproj", "out/"]
RUN dotnet restore "out/app.api.csproj"
COPY . .
WORKDIR "/src/out"
RUN dotnet build "app.api.csproj" -c Debug -o /app/build /p:DebugType=Full

# Stage 2: Publish the application
FROM build AS publish
RUN dotnet publish "app.api.csproj" -c "${BUILD_CONFIGURATION}" -o /app/publish -r "${BUILD_PLATFORM}" /p:UseAppHost=false /p:DebugType=None /p:DebugSymbols=false

# Stage 3: Create the final runtime image
FROM mcr.microsoft.com/dotnet/aspnet:"${DOTNET_VERSION}-alpine" AS runtime
# update the package index
RUN apk update
# install icu-libs for globalization support
RUN apk add --no-cache icu-libs
# RUN apk add --no-cache icu-data-full

WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "app.api.dll"]
